### ISSUE TITLE
Automate web site building with Travis.CI on github

### ISSUE THREAD

**Issue by pyrog** [hotosm/learnosm#328] opened 2015-02-22 06:42 UTC
In order to use Jekyll plugins on [gh-pages](https://pages.github.com) — or to use another static web site generator — we could use Travis.CI to automatically (re)build the site after each _git push_ .

The basic idea is to use the [Travis CI](http://docs.travis-ci.com/user/getting-started/) continuous integration (CI) service. This service is free for open source projects (assuming [fair use](http://travis-ci.com/plans)) and nicely integrates with Github via Service Hooks.

The workflow is as follows:
- `git pull` to the Github repo triggers Travis CI
- Travis CI starts up a virtual machine and installs all required software (mostly Ruby gems)
- We use a custom **rake** task to tell travis CI how to build the static web site and push the updated content back to Github
- Travis CI clones the `master` branch that holds the static HTML **source** pages
- Travis CI runs `jekyll build` (or another web site generator) with the destination in the other branch
- Travis CI does a `git push` of the `gh-pages` branch
- Github Pages starts serving the updates site

**Comment by pyrog** [comment] 2015-02-22 08:18
@jmarlena 
> The documentation and several blogs I've read on customizing your Jekyll site all say that custom plugins don't work with github pages

Yes, see the explanations in [jekyll-travis](https://github.com/mfenner/jekyll-travis/) :smile: 

>  I found a blog post describing a "work around" that requires maintaining a master & gh-pages branch. Below is a link of how they tried to streamline the process of maintaining both branches.
http://blog.nitrous.io/2013/08/30/using-jekyll-plugins-on-github-pages.html

If I understand it well, this process is for geek :wink: 
The **Rakefile** is run manually and locally. This solution is fine for us to test a new concept in a "sandbox" :smile: 

> I will ask the Travis.CI team if they have any different ideas/input on how to use custom Jekyll plugins with github-pages. I will also try experimenting with this.

Could you please test the Makefile and Travis settings described in [jekyll-travis](https://github.com/mfenner/jekyll-travis/) and discuss it with Travis team?
I experimented it in [pyrog/learnosm-sandbox](https://github.com/pyrog/learnosm-sandbox)
See `.travis.yml` and `Rakefile`

The checked steps of the process run fine, "just" the last one need to be fixed with your and Travis team help :smile:
- [x] Changes (`git commit`, `git pull`) on Github repo triggers Travis CI
- [x] Travis CI read the `.travis.yml` file, starts up a virtual machine and installs all required software (mostly Ruby gems listed in `Gemfile`)
```yaml
language: ruby
install:
- bundle install
```
- [x] Travis run the `Rakefile` with a **token** "hidden" in `secure:` to authorize it on GitHub
```yaml
script: bundle exec rake site:deploy
global:
  env:
    secure: DqLVWzSDy0wNqZaQAZVB2Y5Ywcq3ELMjiXZBxzeP5rbHXb+VTlTHHfSGxDFXLeNOAIQLz1Ns8yepicVSh+RUeD4Usv3t6IUaydRGTV38ULiPDTBzy/kNtdPyWh7+b/dL4pscOIxcVB+cs+jubwvqp6d37KuYs1EdF0ryapDRK7k=
```
- [x] Rake clone sources from learnOSM GitHub repository to his "local" repository in the virtual Travis server:
```ruby
def check_destination
  unless Dir.exist? CONFIG["destination"]
    sh "git clone https://#{ENV['GIT_NAME']}:#{ENV['GH_TOKEN']}@github.com/#{USERNAME}/#{REPO}.git #{CONFIG["destination"]}"
  end
end
```
- [x] Rake checkout "locally" both branch
```ruby
    sh "git checkout #{SOURCE_BRANCH}"
    Dir.chdir(CONFIG["destination"]) { sh "git checkout #{DESTINATION_BRANCH}" }
```

- [x] Rake generate the static web pages with the "good" version of Jekyll and all needed plugins
```ruby
    # Generate the site
    sh "bundle exec jekyll build"
```
- [ ] Rake commit "locally" all generated files
```ruby
    # Commit and push to github
    sha = `git log`.match(/[a-z0-9]{40}/)[0]
    Dir.chdir(CONFIG["destination"]) do
      sh "git add --all ."
      sh "git commit -m 'Updating to #{USERNAME}/#{REPO}@#{sha}.'"
```

- [ ] Rake push his "local" repository (on the Travis virtual server) to the `gh-pages` (on learnOSM GitHub repository):
```ruby
      sh "git push origin #{DESTINATION_BRANCH}"
      puts "Pushed updated branch #{DESTINATION_BRANCH} to GitHub Pages"
    end
  end
end
```

You can see what Travis is doing: https://travis-ci.org/pyrog/learnosm-sandbox

**Comment by pyrog** [comment] 2015-02-22 08:34
Probably this rakefile is too complicated for Travis newbies like us? :laughing:
We could try the Makefile described in http://blog.nitrous.io/2013/08/30/using-jekyll-plugins-on-github-pages.html ?

**Comment by jmarlena** [comment] 2015-02-23 14:17
Hey @pyrog! I appreciate the work you've done here. 

The authentication error you get is interesting in part because I've been getting different errors when I've tried setting this up with my own "sandbox" version of the site that I've downloaded locally as testlearnosm. 

According to my email exchange with Travis CI folks, my errors seem to be from getting the right gem dependencies. My proposed solution is to experiment again with Bundler (gem package manager). 

This is my current understanding but I will test it again; I will ask about the rakefile though & try reproducing what you've done here too.

**Comment by pyrog** [comment] 2015-02-24 19:17
> my errors seem to be from getting the right gem dependencies

I haven't errors with gems, only with the token: Travis is not recognize as "myself" so it can't `git push` to the `gh-pages` branch of "my" "sandbox".

Does your token is recognized by Travis/Github?
How did you set it?

**Comment by jmarlena** [comment] 2015-02-25 07:42
@pyrog

I am not having trouble with the token. I forget how I set it up though.
It's confusing in part because there's a Travis token and an Access token.

   - Travis token: Go to the *Profile* tab on your Accounts
   <https://travis-ci.org/profile> page
   - Access token: gem install travis && travis login && travis token or
   manually via the API <https://api.travis-ci.org>.

More info on differences here:
http://blog.travis-ci.com/2013-01-28-token-token-token

**Comment by jmarlena** [comment] 2015-02-26 05:51
Still at a lost for why it's still failing! I've emailed the Travis CI support team for help but I am wondering if anyone else can see what the problem is. 

https://travis-ci.org/jmarlena/learnosm/builds/52229960

Here's the repo with the travis.yml, Gemfile, Gemfile.lock, config.yml and Rakefile.
https://github.com/jmarlena/learnosm/tree/issue262

Any idea what the problem is?

Ideas:
Is the Rakefile too simple?
@Pyrog has suggested another Rakefile (I tested his Rakefile, changing the user info and it still doesn't work):
https://github.com/pyrog/learnosm-sandbox/blob/master/Rakefile

Does it have something to do with the "exclude: [vendor]" line I added to the config.yml file:
https://github.com/jmarlena/learnosm/blob/issue262/_config.yml#L1

 This was recommended in Jekyll Issue2938 to eliminate the last error that read:
"Invalid date '0000-00-00': Post '/vendor/bundle/ruby/2.1.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the filename)."

https://github.com/jekyll/jekyll/issues/2938

**Comment by jmarlena** [comment] 2015-02-26 06:52
@pyrog 
Looks like the last build passed below. So you figured out which token to use? 
https://travis-ci.org/pyrog/learnosm-sandbox

**Comment by pyrog** [comment] 2015-02-26 08:22
@jmarlena 
> Looks like the last build passed below. So you figured out which token to use? 

The token was "good". :smile: 
The issue came from passing this token from `.travis.yml` to the `Rakefile` via **environnement variables**.
Theses variables (`GIT_NAME`, `GIT_EMAIL`, `GIT_TOKEN `) are not set so the `Rakefile` failed.
So I "fix" this in writing directly the token inside the `Rakefile`:

Modified `Rakefile` that work
```python
   # WARNING: GitHub token is in clear !!
   # use this just for test purpose

    puts "Cloning with token"
    sh "git clone https://pyrog:My012Secret4567Token01a1b2c3@github.com/#{USERNAME}/#{REPO}.git #{CONFIG["destination"]}"
```

"Normal" `.travis.yml` that fail !
```yaml
# GIT_NAME, GIT_EMAIL and GIT_TOKEN are encrypted in the secure key
global:
  env:
    secure: F5Sng/rhcLI2eY8G+S1D06VGJrjllQIHJSJKAACyogv3OW4mCS1uFvxuRefEFz1b5kslOCvSlezgZUKi3o5VrIm/WOriZ1bCrpi7DmCyihZwFMtVwGvTDI7TJtUmRTviAb1OFpEWdfLv653GXSABsehc16f5/RyURMONOVe0DX0=
```

Test `.travis.yml` that fail too !
```yaml
# WARNING: GIT_NAME, GIT_EMAIL and GIT_TOKEN are visible
# Use this just for test purpose
global:
  env:
    - "GIT_NAME=pyrog"
    - "GIT_EMAIL=pyrog@laposte.net"
    - "GIT_TOKEN=~My_S3cr3t°T0ken!"
```

**Comment by pyrog** [comment] 2015-02-26 08:34
@jmarlena 
> Here's the repo with the travis.yml, Gemfile, Gemfile.lock, config.yml and Rakefile. https://github.com/jmarlena/learnosm/tree/issue262
Ideas:
Is the Rakefile too simple?

You travis config file don't call your `Rakefile` :wink: 

You should call it as following:
```yaml
install:
- bundle install
script: bundle exec rake
```
* `bundle install` install rake (The `Gemfile` contain `gem "rake"`)
* `script: bundle exec rake` call **rake** that read and execute the content of the `Rakefile`

**Comment by jmarlena** [comment] 2015-03-03 03:13
The latest Jekyll Build error tells me:

'''Don't know how to build task 'default'

/home/travis/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `eval'

/home/travis/.rvm/gems/ruby-2.0.0-p598/bin/ruby_executable_hooks:15:in `<main>'

(See full trace by running task with --trace)

The command "bundle exec rake" exited with 1."'''

**Comment by jmarlena** [comment] 2015-03-06 18:02
Hey @pyrog! Any ideas on why this isn't working?

**Comment by jmarlena** [comment] 2015-03-16 22:03
Got Travis CI to work in my version of the repo. 
https://travis-ci.org/jmarlena/learnosm/builds/54403037

It might need more tweaking to fit the proposed workflow below. Another configuration setting is to add notifications to an email or chat room. Do we want to add notifications? 

**New Proposed Workflow as described by ThinkShout:**
http://thinkshout.com/blog/2014/08/deployment-workflow-travis-jekyll-travis-s3/ 

1) "Make a commit to the master branch. This can be done directly in GitHub, using Prose.io, or the old fashioned way in your own working copy.Note that new features are built in feature branches which do not trigger a build, and are merged into master only when they are ready for review."

2) "The changes are automatically pushed to our staging site for review within a couple minutes.When everything looks good, a pull request is opened comparing master to live."

3) "After any final discussions are complete, the pull request is merged and the code is pushed to [Github Pages]"

@pyrog @wonderchook @althio Any thoughts on the proposed workflow and whether it makes sense for learnosm?

**Comment by wonderchook** [comment] 2015-03-26 03:11
@dodobas what do you think of the workflow above?

**Comment by pyrog** [comment] 2015-04-01 09:06
@jmarlena 
> Don't know how to build task 'default'

In your rakefile, there is no default task :wink:

You could call Rake with the name of the task used to **"deploy"** the static web site:
```ruby
install:
- bundle install
script: bundle exec rake deploy
```

If you are not familiar with Rake and [Rakefile](http://ruby-doc.org/core-1.9.3/doc/rake/rakefile_rdoc.html), you could use any script supported by Travis-CI.
See examples with shell, grunt… : [automatically build on travis](https://github.com/mapillary/traffico/issues/33)

PS: the rakefile that I (try) to use could be run locally (`rake page` to create a new page, `rake serve` to build and start the local web server…) or remotely (`rake deploy` to get a copy of the site, build it and push it to github gh-pages branch)

**Comment by althio** [comment] 2015-05-07 13:19
@pyrog @jmarlena 
Apologies for not being responsive. I like the idea but I am not able to answer specifically on the proposed workflow.
Shall we make it live on one of your sandbox? We have so many things that we want to test: workflow, structure, translation, images...

**Comment by jmarlena** [comment] 2015-05-24 05:59
@althio It's live on @pyrog 's sandbox site. I have it working on issue#328 of my repo too.

**Comment by Nick-Tallguy** [comment] 2017-06-09 22:31
Closing as stale. Staging site is using a form of automation. Something of the travis type could be used is someone is willing to champion and work on it.

**Closed by Nick-Tallguy** 2017-06-09 22:31 UTC
