### ISSUE TITLE
uBlock blocks text on buttons

### ISSUE THREAD

**Issue by rugk** [hotosm/learnosm#604] opened 2020-03-17 14:30 UTC
![grafik](https://user-images.githubusercontent.com/11966684/76861286-a6075600-685c-11ea-92fb-7dce822f4846.png)

at https://learnosm.org/en/

## system

Firefox 74 on Linux/Fedora
many add-ons installed, but nothing special seems to be blocked.

**Comment by rugk** [comment] 2020-03-17 14:31
Ah okay, found the issue: It's uBlock origin.

It blocks that, because you named it "ads", the ID at least. And well… that's blocked.

**Comment by michael63-osm** [comment] 2020-03-17 16:19
@rugk Could you please give our staging site http://nick-tallguy.github.io/en/ a try? I just changed those subdivision names - the coloured buttons at the top are no advertisements anyway.

**Comment by Nick-Tallguy** [comment] 2020-03-17 17:15
Not sure if this is relevant, but yesterday I was updating the site using a Raspberry Pi running 32bit Raspbian, and suffered this problem. At the time I assumed it was because I was trying to get the machine to do too much.
Today I'm using a 64 bit laptop running Ubuntu 18.04 and all is working fine. 
I'll try my raspberry pi again shortly to see if the problem is persisting there.

**Comment by Nick-Tallguy** [comment] 2020-03-17 17:18
Yes - still got the problem on the raspberry pi - using Chromium!  May be a 32 bit problem ? I have had problems in the past with other sites and the raspberry pi

**Comment by rugk** [comment] 2020-03-19 14:50
> Could you please give our staging site http://nick-tallguy.github.io/en/ a try? I just changed those subdivision names - the coloured buttons at the top are no advertisements anyway.

Yes, works.

**Comment by Nick-Tallguy** [comment] 2020-03-20 01:15
Hi,  
Having investigated a little more.  
Using a Raspberry Pi, 32 bit running raspbian. Using Chromium, the site does not display the text on the 'buttons', but click on uBlock, then switch off 'cosmetic filtering for the site', and then refresh the web page, and the text appears.

**Comment by rugk** [comment] 2020-03-20 20:11
Could you maybe discuss this in a different issue? This is totally off-topic…

**Comment by matkoniecz** [comment] 2021-12-22 09:49
@rugk This seems fixed now.

**Closed** 2021-12-23 21:53 UTC
